# Generated by Django 3.2.9 on 2021-11-30 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(related_name='chat', to=settings.AUTH_USER_MODEL, verbose_name='участкника чата')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название города')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название облости')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Навык')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название спецальности')),
                ('professional_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speciality', to='api.professionalarea', verbose_name='Професианальная область')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('discription', models.TextField(verbose_name='Описание вакансии')),
                ('salary', models.IntegerField(null=True, verbose_name='Зарплата')),
                ('experience', models.IntegerField(choices=[(1, 'Нет опыта'), (2, 'До 1 года'), (3, 'От 1 до 3 лет'), (4, 'От 3 до 6 лет'), (5, 'Более 6 лет')], verbose_name='Опыт работы')),
                ('education', models.IntegerField(choices=[(1, 'Среднее'), (2, 'Среднее спецальное'), (3, 'Неполное высшие'), (4, 'Высшее')], verbose_name='Образование')),
                ('type_employment', models.IntegerField(choices=[(1, 'Полная занятость'), (2, 'Частичная занятость'), (3, 'Стажировка'), (4, 'Проектная работа'), (5, 'Волонтерство')], verbose_name='Тип занятости')),
                ('work_schedule', models.IntegerField(choices=[(1, 'Полный день'), (2, 'Сменный режим'), (3, 'Гибкий график'), (4, 'Вахтовый метод')], verbose_name='График работы')),
                ('remote_work', models.BooleanField(default=False, verbose_name='Удаленная работа')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to=settings.AUTH_USER_MODEL, verbose_name='Автор вакансии')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancy', to='api.location', verbose_name='Метоположение')),
                ('skills', models.ManyToManyField(related_name='vacancy', to='api.Skill', verbose_name='Навыки')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancy', to='api.speciality', verbose_name='Спецальность')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название должности')),
                ('salary', models.IntegerField(null=True, verbose_name='Зарплата')),
                ('experience', models.IntegerField(choices=[(1, 'Нет опыта'), (2, 'До 1 года'), (3, 'От 1 до 3 лет'), (4, 'От 3 до 6 лет'), (5, 'Более 6 лет')], verbose_name='Опыт работы')),
                ('education', models.IntegerField(choices=[(1, 'Среднее'), (2, 'Среднее спецальное'), (3, 'Неполное высшие'), (4, 'Высшее')], verbose_name='Образование')),
                ('type_employment', models.IntegerField(choices=[(1, 'Полная занятость'), (2, 'Частичная занятость'), (3, 'Стажировка'), (4, 'Проектная работа'), (5, 'Волонтерство')], verbose_name='Тип занятости')),
                ('work_schedule', models.IntegerField(choices=[(1, 'Полный день'), (2, 'Сменный режим'), (3, 'Гибкий график'), (4, 'Вахтовый метод')], verbose_name='График работы')),
                ('remote_work', models.BooleanField(default=False, verbose_name='Удаленная работа')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resume', to='api.location', verbose_name='Метоположение')),
                ('skills', models.ManyToManyField(related_name='resume', to='api.Skill', verbose_name='Навыки')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resume', to='api.speciality', verbose_name='Спецальность')),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Не просмотрен'), (2, 'Просмотрен'), (3, 'Отказ'), (4, 'Приглашен'), (5, 'Архив')], verbose_name='Статус отклика')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respomses', to='api.resume', verbose_name='Резюме')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.vacancy', verbose_name='Вакансия')),
            ],
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message', to=settings.AUTH_USER_MODEL, verbose_name='Автор Сообщения')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massage', to='api.chat', verbose_name='Чат')),
            ],
        ),
    ]
