# Generated by Django 3.2.9 on 2021-12-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чат'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Местоположение', 'verbose_name_plural': 'Местоположение'},
        ),
        migrations.AlterModelOptions(
            name='massage',
            options={'verbose_name': 'Сообщения', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='professionalarea',
            options={'verbose_name': 'Професианальная облость', 'verbose_name_plural': 'Професианальная облость'},
        ),
        migrations.AlterModelOptions(
            name='responses',
            options={'verbose_name': 'Отклики', 'verbose_name_plural': 'Отклики'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Навыки', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'Спецализация', 'verbose_name_plural': 'Спецализация'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансия'},
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зарплата'),
        ),
    ]
