# Generated by Django 3.2.9 on 2021-12-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211201_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='status',
            field=models.IntegerField(choices=[(1, 'Не просмотрен'), (2, 'Просмотрен'), (3, 'Отказ'), (4, 'Приглашен'), (5, 'Архив')], default=1, verbose_name='Статус отклика'),
        ),
    ]
