# Generated by Django 3.2.9 on 2021-12-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_responses_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-id'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансия'},
        ),
    ]
