# Generated by Django 3.2.9 on 2022-02-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_vacancy_short_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='about_me',
            field=models.TextField(null=True, verbose_name='О себе'),
        ),
    ]
