# Generated by Django 3.2.9 on 2021-11-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.BigIntegerField(default=0, unique=True, verbose_name='Номер телефона'),
        ),
    ]
